services:
  app:
    container_name: architecture_a1_app
    image: web_app
    build:
      context: .
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
    volumes:
      - .:/app:cached
      - deps:/app/deps
      - _build:/app/_build
    depends_on:
      - mongo
    command: mix phx.server

  mongo:
    container_name: architecture_a1_mongo
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  deps:
  _build:
  mongo_data:
