LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule log_config_module modules/mod_log_config.so
ErrorLog /dev/null
ServerName localhost
CustomLog /dev/null common

<VirtualHost *:80>
    ServerName localhost

    ProxyPreserveHost On
    ProxyRequests Off
    ProxyVia On

    <Proxy *>
        Require all granted
    </Proxy>

    ProxyPass / http://app:4000/
    ProxyPassReverse / http://app:4000/
</VirtualHost>